DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  age INTEGER(3) NOT NULL
);

CREATE TABLE ADDRESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  street VARCHAR(50) NOT NULL,
  city VARCHAR(50) DEFAULT NULL,
  state VARCHAR(50) DEFAULT NULL,
  country VARCHAR(50) DEFAULT NULL,
  zipcode VARCHAR(50) DEFAULT NULL
);